# Problem Statement – Gradient Boosting Classifier

- A telecom company wants to reduce the number of customers leaving its services. Customer churn can cause significant revenue loss, so the company needs a system that can identify customers who are likely to leave.
The objective of this project is to build a Gradient Boosting Classifier that predicts whether a customer will churn or stay based on their personal, service, billing, and contract information.

In [53]:
import pandas as pd
import numpy as np

In [54]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/gradient_boosting_customer_churn_10000.csv")

In [55]:
df.head()

,Age,Monthly_Charges,Total_Charges,Tenure_Months,Number_of_Services,Support_Calls,Contract_Length,Payment_Delay_Days,Churn
0,63,61.33,10279.33,32,7,2,24,2,No
1,20,115.96,1713.44,27,1,4,1,20,Yes
2,46,92.05,10890.48,1,2,4,12,17,Yes
3,52,95.26,7126.69,58,4,4,36,15,Yes
4,56,147.00,12255.65,17,7,7,12,13,Yes

In [10]:
df.shape

(10000, 9)

In [14]:
df.columns

Index(['Age', 'Monthly_Charges', 'Total_Charges', 'Tenure_Months',
       'Number_of_Services', 'Support_Calls', 'Contract_Length',
       'Payment_Delay_Days', 'Churn'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 10000 non-null  int64
 1   Monthly_Charges     10000 non-null  float64
 2   Total_Charges       10000 non-null  float64
 3   Tenure_Months       10000 non-null  int64
 4   Number_of_Services  10000 non-null  int64
 5   Support_Calls       10000 non-null  int64
 6   Contract_Length     10000 non-null  int64
 7   Payment_Delay_Days  10000 non-null  int64
 8   Churn               10000 non-null  object
dtypes: float64(2), int64(6), object(1)
memory usage: 703.3+ KB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.isnull().sum()

Age                   0
Monthly_Charges       0
Total_Charges         0
Tenure_Months         0
Number_of_Services    0
Support_Calls         0
Contract_Length       0
Payment_Delay_Days    0
Churn                 0
dtype: int64

In [15]:
df.describe()

,Age,Monthly_Charges,Total_Charges,Tenure_Months,Number_of_Services,Support_Calls,Contract_Length,Payment_Delay_Days
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,43.432400,85.088660,7735.098163,36.625100,4.004500,4.976500,18.295900,15.065500
std,15.027169,37.468756,4148.071109,20.836184,1.987077,3.151181,13.050003,9.013231
min,18.000000,20.040000,502.450000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,30.000000,52.177500,4121.222500,19.000000,2.000000,2.000000,12.000000,7.000000
50%,43.000000,85.860000,7716.620000,37.000000,4.000000,5.000000,24.000000,15.000000
75%,57.000000,117.450000,11327.785000,55.000000,6.000000,8.000000,24.000000,23.000000
max,69.000000,149.950000,14997.600000,72.000000,7.000000,10.000000,36.000000,30.000000

In [16]:
df["Churn"].value_counts()

Churn
Yes    6044
No     3956
Name: count, dtype: int64

# Separate Features and Target

In [17]:
X = df.drop("Churn", axis=1)

y = df["Churn"].map({
    "No": 0,
    "Yes": 1})

print("X Shape:", X.shape)
print("y Shape:", y.shape)

X Shape: (10000, 8)
y Shape: (10000,)

# Train-Test Split

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_test.shape)
print(y_train.shape)

(2000, 8)
(8000, 8)
(8000,)
(2000,)

# Create Gradient Boosting Model

In [27]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model=GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42)
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(random_state=42)

# Prediction

In [29]:
y_pred=gb_model.predict(X_test)
print(y_pred[:10])

[0 1 0 0 1 0 0 1 1 1]

# Accuracy

In [33]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.9375

# Confusion Matrix

In [36]:
from sklearn.metrics import confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
print("Confusion_matrix:",cm)

Confusion_matrix: [[2952  219]
 [ 281 4548]]

# Classification Report

In [37]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.93      0.92      3171
           1       0.95      0.94      0.95      4829

    accuracy                           0.94      8000
   macro avg       0.93      0.94      0.93      8000
weighted avg       0.94      0.94      0.94      8000

# GridSearchCV

In [39]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100, 150],
    "learning_rate": [0.01, 0.1, 0.2],
    "max_depth": [2, 3, 4],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]}

In [41]:
grid_search = GridSearchCV(
    estimator=GradientBoostingClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1)
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [2, 3, 4], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100, 150]},
             scoring='accuracy')

# Best Parameters

In [42]:
print("Best Parameters:")
print(grid_search.best_params_)

Best Parameters:
{'learning_rate': 0.2, 'max_depth': 2, 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 50}

# Best CV Score

In [43]:
print("Best CV Accuracy:")
print(grid_search.best_score_)

Best CV Accuracy:
0.9324999999999999

# Best Model

In [45]:
best_model = grid_search.best_estimator_
y_pred_best = best_model.predict(X_test)

# Final Evaluation

In [47]:
print("Final Accuracy:",
      accuracy_score(y_test, y_pred_best))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best))

Final Accuracy: 0.94

Confusion Matrix:
[[2962  209]
 [ 271 4558]]

In [48]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred_best))

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      3171
           1       0.96      0.94      0.95      4829

    accuracy                           0.94      8000
   macro avg       0.94      0.94      0.94      8000
weighted avg       0.94      0.94      0.94      8000