# Project– Loan Approval Prediction Using SVM
# Problem Statement
- A financial institution receives loan applications from customers with different financial and personal characteristics. Manually evaluating every application can be time-consuming and may lead to inconsistent decisions.

The objective of this project is to build a machine learning classification model using Support Vector Machine (SVM) to predict whether a customer's loan application will be Approved or Not Approved based on their information.

# Input Features
- Age
- Annual Income
- Credit Score
- Employment Years
- Loan Amount
- Debt-to-Income Ratio
- Existing Loans
- Dependents

# Target Variable
#  Loan_Approved
- Yes → Loan Approved
- No → Loan Not Approved

In [43]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/svm_loan_approval_10000.csv")

In [4]:
df.head()

,Age,Annual_Income,Credit_Score,Employment_Years,Loan_Amount,Debt_to_Income_Ratio,Existing_Loans,Dependents,Loan_Approved
0,56,109614,636,10,300528,0.65,5,5,Yes
1,46,108116,781,11,365687,0.77,0,2,No
2,32,76235,485,28,240428,0.24,4,1,No
3,60,34855,468,10,306366,0.69,0,5,No
4,25,56169,559,18,264487,0.63,3,1,No

In [5]:
df.shape

(10000, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  int64
 1   Annual_Income         10000 non-null  int64
 2   Credit_Score          10000 non-null  int64
 3   Employment_Years      10000 non-null  int64
 4   Loan_Amount           10000 non-null  int64
 5   Debt_to_Income_Ratio  10000 non-null  float64
 6   Existing_Loans        10000 non-null  int64
 7   Dependents            10000 non-null  int64
 8   Loan_Approved         10000 non-null  object
dtypes: float64(1), int64(7), object(1)
memory usage: 703.3+ KB

In [8]:
df.columns

Index(['Age', 'Annual_Income', 'Credit_Score', 'Employment_Years',
       'Loan_Amount', 'Debt_to_Income_Ratio', 'Existing_Loans', 'Dependents',
       'Loan_Approved'],
      dtype='object')

In [9]:
df.describe()

,Age,Annual_Income,Credit_Score,Employment_Years,Loan_Amount,Debt_to_Income_Ratio,Existing_Loans,Dependents
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,41.054000,84427.786600,575.452700,15.246600,255233.812000,0.422862,2.517600,2.497800
std,13.484104,37782.070869,159.751803,8.935915,143246.421835,0.216948,1.713997,1.710055
min,18.000000,20002.000000,300.000000,0.000000,5157.000000,0.050000,0.000000,0.000000
25%,30.000000,51106.000000,435.000000,8.000000,130212.250000,0.240000,1.000000,1.000000
50%,41.000000,84381.000000,575.000000,15.000000,258042.500000,0.420000,3.000000,3.000000
75%,53.000000,116753.750000,713.000000,23.000000,380207.500000,0.610000,4.000000,4.000000
max,64.000000,149994.000000,850.000000,30.000000,499932.000000,0.800000,5.000000,5.000000

In [11]:
df.isnull().sum()

Age                     0
Annual_Income           0
Credit_Score            0
Employment_Years        0
Loan_Amount             0
Debt_to_Income_Ratio    0
Existing_Loans          0
Dependents              0
Loan_Approved           0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [24]:
df["Loan_Approved"].value_counts()

Loan_Approved
No     5630
Yes    4370
Name: count, dtype: int64

# Separate X and y

In [13]:
X = df.drop("Loan_Approved", axis=1)
y = df["Loan_Approved"].map({
    "No": 0,
    "Yes": 1})

print(X.shape)
print(y.head())

(10000, 8)
0    1
1    0
2    0
3    0
4    0
Name: Loan_Approved, dtype: int64

# Train-Test Split

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(2000, 8)
(8000, 8)
(2000,)
(8000,)

# StandardScaler

In [26]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_scaler=scaler.fit_transform(X_train)
X_test_scaler=scaler.transform(X_test)

# Apply SVM

In [29]:
from sklearn.svm import SVC
model = SVC(
    kernel="rbf",
    C=1.0,
    gamma="scale",
    random_state=42)
model.fit(X_train_scaler, y_train)

SVC(random_state=42)

# Prediction

In [31]:
y_pred=model.predict(X_test_scaler)
print(y_pred[:10])

[0 1 0 1 1 0 0 1 1 0]

# Evaluation

In [33]:
from sklearn.metrics import (accuracy_score,confusion_matrix,classification_report)

In [36]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.8195

In [38]:
cm=confusion_matrix(y_test,y_pred)
print("nConfusion Matrix:",cm)

nConfusion Matrix: [[3815  690]
 [ 754 2741]]

In [42]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.85      0.84      4505
           1       0.80      0.78      0.79      3495

    accuracy                           0.82      8000
   macro avg       0.82      0.82      0.82      8000
weighted avg       0.82      0.82      0.82      8000